# Project information
site_name: "Abhitopia's Blog"
site_description: "Abhitopia's Blog"
site_author: 'Abhishek Aggarwal'
site_url: 'https://abhitopia.com'

nav:
  - Home: index.md
  - About: about.md

# Repository
#repo_name: 'squidfunk/mkdocs-material'
#repo_url: 'https://github.com/squidfunk/mkdocs-material'

# Copyright
copyright: 'Copyright &copy; 2018 Abhishek Aggarwal'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

remote_branch: 'master'  # this will cause gh-deploy to push to master branch

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/abhitopia'
    - type: 'twitter'
      link: 'https://twitter.com/abhitopia'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/abhitopia'
  disqus: 'abhitopia-1'

# Google Analytics
google_analytics:
  - 'UA-126541129-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde